paname: Validate Techniques
on:
  pull_request:
    paths:
      - "data/**"
      - ".github/workflows/validate-techniques.yml"
  push:
    branches: ["main"]
    paths:
      - "data/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jsonschema
      - name: Validate techniques.yaml against schema
        run: |
          python - << 'PY'
          import yaml, sys
          from jsonschema import Draft202012Validator
          with open("data/techniques.schema.yaml") as sf:
              schema = yaml.safe_load(sf)
          with open("data/techniques.yaml") as df:
              data = yaml.safe_load(df)
          v = Draft202012Validator(schema)
          errs = sorted(v.iter_errors(data), key=lambda e: (list(e.path), e.message))
          if errs:
              for e in errs:
                  loc = "/".join(map(str, e.path)) or "(root)"
                  print(f"[SCHEMA] {loc}: {e.message}")
              sys.exit(1)
          print("Schema validation passed.")
          PYste